### PR TITLE
Croatian locale is not cro_CRO. Renamed to hr_HR

### PR DESCRIPTION
**Pull request by pweigand**
Croatian locale is not cro_CRO. Renamed to hr_HR according to IETF tags.
reference: https://en.wikipedia.org/wiki/IETF_language_tag
Changed the translation to include distinct declinations for specific number usages.

### CODE REVIEW

**Comment by caseyjhol** [comment]
@pweigand Can you remove the distribution files and leave only js/i18n/defaults-hr_HR.js?

**Comment by pweigand** [comment]
Not sure if this is what you had in mind? 
https://github.com/silviomoreto/bootstrap-select/pull/1383/commits/89dd03591651268e99c120889b6561832bedb1da

**Comment by caseyjhol** [comment]
Sorry...I meant for you to rebase with your changes on top (i.e. not include the update dist files). That would mean changes to only 2 files:

- `+ js/i18n/defaults-hr_HR.js`
- `- js/i18n/defaults-cro_CRO.js`

**Comment by caseyjhol** [comment]
Available in v1.13.0-alpha.

**Pull request closed without merging**
