### PR TITLE
containsAll searchString Method added

### PR DESCRIPTION
**Pull request by Breeven**
New containsAll method that searches like Datatable search.

For example: "Ap Pi", "pple ie" and "App" matches Item "Apple Pie" 
"Ax Yi" does nicht match the Item "Apple Pie"

### CODE REVIEW

**Review by jybleau — COMMENTED** [review]
Code needs to be reformated to satisfy Quality Review rules, like this:

```javascript
        if (method === 'contains') {
          searchSuccess = string.indexOf(searchString) >= 0;
        } else if (method === 'containsAll') {
          // Contains all parts of the strings seperated by blanks (like Datatable Search)
          var searchArray = searchString.split(' ');
          var notAllMatched = false;
          searchSuccess = false;

          for (var searchSubString in searchArray) {
            searchSuccess = string.indexOf(searchArray[searchSubString]) >= 0;
            if (!searchSuccess) notAllMatched = true;
          }

          if (notAllMatched) searchSuccess = false;
        } else {
          searchSuccess = string.startsWith(searchString);
        }
```

Should also update this doc file `docs/docs/options.md` (section `liveSearchStyle`):

```html
  <tr>
    <td>liveSearchStyle</td>
    <td>string</td>
    <td><code>'contains'</code></td>
    <td>
      <p>When set to <code>'contains'</code>, searching will reveal options that contain the searched text. For example, searching for pl will return both Ap<b>pl</b>e, <b>Pl</b>um, and <b>Pl</b>antain.</p>
      <p>When set to <code>'containsAll'</code>, searching will reveal options that contain all the searched text. For example, searching for "pl pi" will return only Ap<b>pl</b>e <b>Pi</b>e and exclude <b>Pl</b>antain.</p>
      <p>When set to <code>'startsWith'</code>, searching for pl will return only <b>Pl</b>um and <b>Pl</b>antain.</p>
    </td>
  </tr>
```

**Comment by NicolasCARPi** [comment]
@jybleau pretty sure @Breeven moved to greener pastures and will never come back to this PR. For context, his contributions in the past two years: 
2022-10-20-171323_931x232_scrot

2022-10-20-171331_933x234_scrot

**Comment by jybleau** [comment]
Oh! Thanks @NicolasCARPi
I'll create a new PR to replace it instead.

**Comment by NicolasCARPi** [comment]
BTW, you should fix the link to your website on your github profile ;)

Closing this PR at the same time.

**Pull request closed without merging**
