### PR TITLE
add SASS version

### PR DESCRIPTION
**Pull request by bsorem-sugarcrm**
Answers #1199

### CODE REVIEW

**Comment by shehi** [comment]
Can we please get this merged asap? I need SASS as well. Thanks!

**Comment by dhuf** [comment]
+1 for me

**Comment by shehi** [comment]
Ping @silviomoreto

**Comment by silviomoreto** [comment]
@bsorem-sugarcrm I cant test your commit. Can I trust in your PR?

**Comment by bsorem-sugarcrm** [comment]
@silviomereto I hope so! I compiled it to CSS using SASS and manually compared that to the LESS-generated CSS.

**Comment by silviomoreto** [comment]
Ok, it is already accepted. Thanks

**Comment by shehi** [comment]
Dear @silviomoreto , even if it has problems, we - SASS users - will send additional PRs to fix it up :D Thanks for merge. Please make sure you have a release with this inside, so that we could use it with Bower.

**Comment by silviomoreto** [comment]
done 4d47d756e4fadef8483b545c46a6d00097af5013

**Pull request merged**
