### PR TITLE
Add option to insert live search string as new result

### PR DESCRIPTION
**Pull request by Sharnw**
Added a data option `add-results`, which when added to after `live-search` replaces the 'No Results' text with a prompt to 'Add new: <search string>'.

### CODE REVIEW

**Comment by danboh** [comment]
Hi! Any updates on this? I'd really like to add this functionality to my project.

Thanks!

**Comment by Sharnw** [comment]
I've resolved conflicts (finally). Can this go live @silviomoreto ?

**Comment by MrClemRkz** [comment]
This seems awesome. When can we have it on official package?

**Comment by Sharnw** [comment]
I'll merge this with master and push this fork to an npm package if you like, if silvio isn't going to accept the pull request.

**Comment by silviomoreto** [comment]
Hi @Sharnw 
Can you be responsible to merge that and add it to the documentation?

**Comment by Sharnw** [comment]
Alright, on it. Thanks @silviomoreto 

edit:

done :)

**Pull request merged**
