### PR TITLE
Bidirectional CSS.

### PR DESCRIPTION
**Pull request by elad**
Separate direction-dependent styles and conditionalize them on the value of the 'direction' attribute on the 'html' tag. (That is, 'ltr' or 'rtl').

### CODE REVIEW

**Comment by elad** [comment]
@t0xicCode I completely forgot about this - sorry! (using my own fork)

I see this project now uses less instead of regular CSS. Would you like me to adapt it so that it generates CSS similar to what's in this pull request?

**Comment by t0xicCode** [comment]
Sure,

Although I've been more hands off recently. Any improvement is good in my
book.

**Comment by elad** [comment]
@t0xicCode, before I submit a pull request, I'd like to reconsider. Here's `bootstrap-select.less` as adjusted for bidirectional CSS support:

```css
@import "variables";

// Mixins
.cursor-disabled() {
  cursor: not-allowed;
}

// Rules
.bootstrap-select {
  width: 220px \0; /*IE9 and below*/

  // The selectpicker button
  > .dropdown-toggle {
    width: 100%;
    padding-right: 25px;
  }

  // Error display
  .has-error & .dropdown-toggle,
  .error & .dropdown-toggle {
    border-color: @color-red-error;
  }

  &.fit-width {
    width: auto !important;
  }

  &:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
    width: @width-default;
  }

  .dropdown-toggle:focus {
    outline: thin dotted #333333 !important;
    outline: 5px auto -webkit-focus-ring-color !important;
    outline-offset: -2px;
  }
}
/* left-to-right */
html:not([dir=rtl]) {
  .bootstrap-select {
    // The selectpicker button
    > .dropdown-toggle {
      padding-right: 25px;
    }
  }
}
/* right-to-left */
html[dir=rtl] {
  .bootstrap-select {
    // The selectpicker button
    > .dropdown-toggle {
      padding-left: 25px;
    }
  }
}

.bootstrap-select.form-control {
  margin-bottom: 0;
  padding: 0;
  border: none;

  &:not([class*="col-"]) {
    width: 100%;
  }

  &.input-group-btn {
    z-index: auto;
  }
}

// The selectpicker components
.bootstrap-select.btn-group {
  &:not(.input-group-btn),
  &[class*="col-"] {
    float: none;
    display: inline-block;
  }

  .form-inline &,
  .form-horizontal &,
  .form-group & {
    margin-bottom: 0;
  }

  .form-group-lg &.form-control,
  .form-group-sm &.form-control {
    padding: 0;
  }

  // Set the width of the live search (and any other form control within an inline form)
  // see https://github.com/silviomoreto/bootstrap-select/issues/685
  .form-inline & .form-control {
    width: 100%;
  }

  &.disabled,
  > .disabled {
    .cursor-disabled();

    &:focus {
      outline: none !important;
    }
  }

  &.bs-container {
    position: absolute;
    
    .dropdown-menu {
      z-index: @zindex-select-dropdown;
    }
  }

  // The selectpicker button
  .dropdown-toggle {
    .filter-option {
      display: inline-block;
      overflow: hidden;
      width: 100%;
    }

    .caret {
      position: absolute;
      top: 50%;
      margin-top: -2px;
      vertical-align: middle;
    }
  }

  &[class*="col-"] .dropdown-toggle {
    width: 100%;
  }

  // The selectpicker dropdown
  .dropdown-menu {
    min-width: 100%;
    box-sizing: border-box;

    &.inner {
      position: static;
      float: none;
      border: 0;
      padding: 0;
      margin: 0;
      border-radius: 0;
      box-shadow: none;
    }

    li {
      position: relative;

      &.active small {
        color: #fff;
      }

      &.disabled a {
        .cursor-disabled();
      }

      a {
        cursor: pointer;
        -webkit-user-select: none;
           -moz-user-select: none;
            -ms-user-select: none;
                user-select: none;

        &.opt {
          position: relative;
        }

        span.check-mark {
          display: none;
        }

        span.text {
          display: inline-block;
        }
      }
    }

    .notify {
      position: absolute;
      bottom: 5px;
      width: 96%;
      margin: 0 2%;
      min-height: 26px;
      padding: 3px 5px;
      background: rgb(245, 245, 245);
      border: 1px solid rgb(227, 227, 227);
      box-shadow: inset 0 1px 1px fade(rgb(0, 0, 0), 5%);
      pointer-events: none;
      opacity: 0.9;
      box-sizing: border-box;
    }
  }

  .no-results {
    padding: 3px;
    background: #f5f5f5;
    margin: 0 5px;
    white-space: nowrap;
  }

  &.fit-width .dropdown-toggle {
    .filter-option {
      position: static;
    }

    .caret {
      position: static;
      top: auto;
      margin-top: -1px;
    }
  }

  &.show-tick .dropdown-menu li {
    &.selected a span.check-mark {
      position: absolute;
      display: inline-block;
      margin-top: 5px;
    }
  }
}
/* left-to-right */
// We use variables because of the way less quotes parents
@bs: bootstrap-select;
@bg: btn-group;
html:not([dir=rtl]) {
  .@{bs}.@{bg} {
    .@{bs}.@{bg}:not(.input-group-btn),
    .@{bs}.@{bg}[class*="col-"] {
      margin-left: 0;
    }

    // Forces the pull to the right, if necessary
    .@{bs}.@{bg},
    .@{bs}.@{bg}[class*="col-"],
    .row .@{bs}.@{bg}[class*="col-"] {
      .@{bs}.@{bg}.dropdown-menu-right {
        float: right;
      }
    }

    // The selectpicker button
    .dropdown-toggle {
      .filter-option {
        text-align: left;
      }

      .caret {
        right: 12px;
      }
    }

    // The selectpicker dropdown
    .dropdown-menu {
      li {
        a {
          .@{bs}.@{bg}.opt {
            padding-left: 2.25em;
          }
        }

        small {
          padding-left: 0.5em;
        }
      }
    }

    .@{bs}.@{bg}.show-tick .dropdown-menu li {
      .@{bs}.@{bg}.selected a span.check-mark {
        right: 15px;
      }

      a span.text {
        margin-right: 34px;
      }
    }
  }
}
/* right-to-left */
html[dir=rtl] {
  .@{bs}.@{bg} {
    .@{bs}.@{bg}:not(.input-group-btn),
    .@{bs}.@{bg}[class*="col-"] {
      margin-right: 0;
    }

    // Forces the pull to the left, if necessary
    .@{bs}.@{bg},
    .@{bs}.@{bg}[class*="col-"],
    .row .@{bs}.@{bg}[class*="col-"] {
      .@{bs}.@{bg}.dropdown-menu-right {
        float: left;
      }
    }

    // The selectpicker button
    .dropdown-toggle {
      .filter-option {
        text-align: right;
      }

      .caret {
        left: 12px;
      }
    }

    // The selectpicker dropdown
    .dropdown-menu {
      li {
        a {
          .@{bs}.@{bg}.opt {
            padding-right: 2.25em;
          }
        }

        small {
          padding-right: 0.5em;
        }
      }
    }

    .@{bs}.@{bg}.show-tick .dropdown-menu li {
      .@{bs}.@{bg}.selected a span.check-mark {
        left: 15px;
      }

      a span.text {
        margin-left: 34px;
      }
    }
  }
}

.bootstrap-select.show-menu-arrow {
  &.open > .dropdown-toggle {
    z-index: (@zindex-select-dropdown + 1);
  }

  .dropdown-toggle {
    &:before {
      content: '';
      border-left: 7px solid transparent;
      border-right: 7px solid transparent;
      border-bottom: 7px solid @color-grey-arrow;
      position: absolute;
      bottom: -4px;
      display: none;
    }

    &:after {
      content: '';
      border-left: 6px solid transparent;
      border-right: 6px solid transparent;
      border-bottom: 6px solid white;
      position: absolute;
      bottom: -4px;
      display: none;
    }
  }

  &.dropup .dropdown-toggle {
    &:before {
      bottom: auto;
      top: -3px;
      border-top: 7px solid @color-grey-arrow;
      border-bottom: 0;
    }

    &:after {
      bottom: auto;
      top: -3px;
      border-top: 6px solid white;
      border-bottom: 0;
    }
  }

  &.open > .dropdown-toggle {
    &:before,
    &:after {
      display: block;
    }
  }
}
/* left-to-right */
html:not([dir=rtl]) {
  .bootstrap-select.show-menu-arrow {
    .dropdown-toggle {
      &:before {
        right: 9px;
      }

      &:after {
        right: 10px;
      }
    }

    &.pull-right .dropdown-toggle {
      &:before {
        right: 12px;
        left: auto;
      }

      &:after {
        right: 13px;
        left: auto;
      }
    }
  }
}
/* right-to-left */
html[dir=rtl] {
  .bootstrap-select.show-menu-arrow {
    .dropdown-toggle {
      &:before {
        left: 9px;
      }

      &:after {
        left: 10px;
      }
    }

    &.pull-right .dropdown-toggle {
      &:before {
        left: 12px;
        right: auto;
      }

      &:after {
        left: 13px;
        right: auto;
      }
    }
  }
}

.bs-searchbox,
.bs-actionsbox,
.bs-donebutton {
  padding: 4px 8px;
}

.bs-actionsbox {
  width: 100%;
  box-sizing: border-box;

  & .btn-group button {
    width: 50%;
  }
}

.bs-donebutton {
  width: 100%;
  box-sizing: border-box;

  & .btn-group button {
    width: 100%;
  }
}
/* left-to-right */
html:not([dir=rtl]) {
  .bs-donebutton {
    float: left;
  }
}
/* right-to-left */
html[dir=rtl] {
  .bs-donebutton {
    float: right;
  }
}

.bs-searchbox {
  & + .bs-actionsbox {
    padding: 0 8px 4px;
  }

  & .form-control {
    margin-bottom: 0;
    width: 100%;
    float: none;
  }
}

select.bs-select-hidden,
select.selectpicker {
  display: none !important;
}

select.mobile-device {
  position: absolute !important;
  top: 0;
  display: block !important;
  width: 100%;
  height: 100% !important;
  opacity: 0;
}
/* left-to-right */
html:not([dir=rtl]) {
  select.mobile-device {
    left: 0;
  }
}
/* right-to-left */
html[dir=rtl] {
  select.mobile-device {
    right: 0;
  }
}
```

If you take a moment to look at the changes, you'll see that some parts had to be separated. For a really ugly example, look for the left-to-right/right-to-left support for .bootstrap-select.button-group.

So while this will support bidirectional CSS in one file determined during runtime, since this project uses less maybe a different approach is more suitable, namely, using less macros to generate two files - one with CSS for left-to-right and one with CSS for right-to-left.

Let me know which one works for you - the latter will be much cleaner, but will require conditional CSS loading by developers who want to support both LTR and RTL. I'll submit a pull request with the proper changes then.

**Comment by elad** [comment]
Obsoleted by #1120.

**Pull request closed without merging**
