### PR TITLE
bugfix - "Nothing Selected" with 1 item selected with data-selected-text-format

### PR DESCRIPTION
**Pull request by jeffbeagley**
…a-selected-text-format was provided, the selectbox would say "nothing selected" when one item was.

### CODE REVIEW

**Comment by jeffbeagley** [comment]
This pull request conflicts with using count > 1, back to the drawing board!

**Comment by caseyjhol** [comment]
Can you provide an example of the bug?

**Comment by jeffbeagley** [comment]
Here's a fiddle. You can see with 1 item selected, and option "count" provided, it still states nothing selected.

https://jsfiddle.net/jeffbeagley/DTcHh/51050/

**Comment by caseyjhol** [comment]
Ah - I see. This is only happening with v1.13.0-beta. Should be an easy fix.

**Comment by caseyjhol** [comment]
Fixed here: https://github.com/snapappointments/bootstrap-select/commit/41ebe2220e82279200937c51ef5c8ffb90fe2637. Available in the v1.13.0-dev branch in that repo. Will be available in v1.13.0 or v1.13.0-beta.1.

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Pull request closed without merging**
