### PR TITLE
Lazy loading (extracted changes from provided archive, see issue #1665)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by anatoly-mytrucking** [comment]
For #1665

**Comment by holtkamp** [comment]
Experienced the same performance reductions when large amount of `<select class="selectpicker"/>` are involved. The number of options (6) is not so large though.

**Comment by anatoly-mytrucking** [comment]
@holtkamp It's a little bit "dirty" PR and I'm not sure about all changes. I just converted changes provided in #1665 into a commit so they can be easily inspected by other developers.

**Comment by anatoly-mytrucking** [comment]
Did a proper extraction of changes. Previous time I did it on the top of upstream's master, now I used v1.12.2

Fixed couple of issues.

**Comment by holtkamp** [comment]
Nice, I did some benchmarking with an e-commerce page that uses bootstrap select to allow to:
- indicate quantity of article
- indicate variations of article

For each article, 6 base variations are available. So for 1 article, 12 `<select/>` elements are used

I used this JavaScript file: https://github.com/MyTrucking/bootstrap-select/blob/2f16cb3a094c8b14844a8a10dd03874704abcdcc/js/bootstrap-select.js


FireFox
- 1 article, 12 select elements: ~130ms => ~130ms
- 10 articles, 120 select elements: 610ms => ~590ms
- 70 articles, 960 select elements: ~3800ms => ~2800ms

Chrome
- 1 article, 12 select elements: ~130ms => ~130ms
- 10 articles, 120 select elements: ~380ms => ~380ms
- 70 articles, 960 select elements: ~3800ms => ~2800ms

(I choose a maximum of 70 articles to test with since that is the maximum amount of articles displayed on a real-life page)

So there seems a small improvement but since the browser still "hangs" for around 3 seconds, I think other improvements are required. Maybe for Internet Explorer this PR is a life saver, but otherwise we should maybe consider postponing loading until an element is within the viewport of the browser...

**Comment by anatoly-mytrucking** [comment]
@holtkamp just to be sure, have you added `data-lazy-load-li-elements="true"` to your `<select>` tags?

I think there's a room to improve this solution also, but I'm not sure if I will do it.
For postponing loading until an element is within the viewport of the browser you can try https://github.com/hakubo/Sloth and initialise bootstrap-select component using JS instead `data-` attributes.

**Comment by holtkamp** [comment]
>just to be sure, have you added data-lazy-load-li-elements="true" to your <select> tags?

oops..., no I did not 😭 Guess its bed time 😄 . Just added `data-lazy-load-li-elements="true"` and this indeed changes the results significantly! Not such improvements as reported in https://github.com/silviomoreto/bootstrap-select/issues/1665#issue-211820788, but that may be due to the way of measuring (I use console.time() and just refresh a few times).

Chrome

1 article, 12 select elements: ~130ms => ~70ms
10 articles, 120 select elements: ~380ms => ~200ms
70 articles, 960 select elements: ~3800ms => ~1200ms

So +1 to merge!

**Comment by holtkamp** [comment]
@anatoly-mytrucking, after receiving feedback from users, we decided to have dropdown menus actually dropdown when hovering the mouse over it, not only when clicking it. 

We realized this using: https://github.com/CWSpear/bootstrap-hover-dropdown

It seems this way of activating the menu, does not trigger the lazy loading of the `<li/>` items to kick in. Maybe there is another event than `click` to listen for here: https://github.com/silviomoreto/bootstrap-select/pull/1667/files#diff-ff31d80eb2d28b06752ee372aa065210R411 ?

Or any otherway to detect when the dropdown menu is activated. 

Clicking: activates dropdown menu AND triggers lazy loading
screen shot 2017-05-04 at 17 39 07

Hovering: activates dropdown menu but does not trigger lazy loading: empty menu
screen shot 2017-05-04 at 17 38 56

**Comment by anatolykazantsev** [comment]
@holtkamp I switched from `show.bs.dropdown` event to `click.dropdown.data-api` one to get correct sequence of events when live search is on. But you can change it back to `show.bs.dropdown` if it works ok for you. Or maybe there's some `*.dropdown.data-api` for hovering.

**Comment by holtkamp** [comment]
@anatolykazantsev ok, might be an idea to make this event configurable, defaulting to `click.dropdown.data-api`. But that would/should be a different PR. 

@silviomoreto what do you think? Can this be merged?

**Comment by holtkamp** [comment]
@caseyjhol any idea on when a "final" `1.13.0` can be expected?

**Comment by holtkamp** [comment]
@anatolykazantsev it seems https://github.com/silviomoreto/bootstrap-select/releases/tag/v1.13.0-alpha contains some performance improvements as well

**Comment by frg** [comment]
Any update on this PR?

**Pull request merged**
