### PR TITLE
Html tag option

### PR DESCRIPTION
**Pull request by Cactusbone**
html tag option, to decide between using `span` or `i`

### CODE REVIEW

**Comment by caseyjhol** [comment]
What are the issues with using span?

**Comment by Cactusbone** [comment]
I'll check locally, since we're using material design icons, all the examples uses `i` but i'll check if default styles really uses it.

**Comment by Cactusbone** [comment]
we're migrating from 1.5.4 to the latest version so keeping `i` was easier during migration :)

**Comment by Cactusbone** [comment]
i cleaned up our css to not use i . i'll close this pull request :)

**Pull request closed without merging**
