### PR TITLE
add live-search-style containsAll option, with doc

### PR DESCRIPTION
**Pull request by jybleau**
Replaces #2470 PR and targets the latest dev branch.

`containsAll` value for `live-search-style` option.

**Example:** 
Searching "Ap Pi", "pple ie" and "App" matches item like "Apple Pie".

Compiled with `grunt` and tested on personal project.

The doc is updated accordingly.

### CODE REVIEW

**Review by hanishsingla — APPROVED** [review]

**Comment by NicolasCARPi** [comment]
@jybleau Thank you for your contribution. It would be great if this new behavior could be tested automatically. Have a look at the `cypress` folder. It would also help validate your code.

**Comment by jybleau** [comment]
@NicolasCARPi sure, I'll have a look and add some tests. Thanks.

**Comment by jybleau** [comment]
@NicolasCARPi, my first time with Cypress, quite cool!
I covered when `live-search-style` is equal to `containsAll`. It seems correctly done to me...  but waiting for your feedback.

**Comment by NicolasCARPi** [comment]
Great job @jybleau. Now you can extend that to also test for the "contains" mode, so the test suite shows the difference between the two search modes ;)

**Comment by jybleau** [comment]
@NicolasCARPi, added the checks to cover the default "contains" search style. Didn't like my first version hence the refactor commit, haha!

**Comment by NicolasCARPi** [comment]
Thank you!

**Pull request merged**
