### PR TITLE
Prefix in title (Icon and text label on button)

### PR DESCRIPTION
**Pull request by cowabunga1**
Hi, friend!

I just added functionality to paste prefix in title (icon and text label).

Cool?

myscreen web

### CODE REVIEW

**Comment by RockyNiu** [comment]
This function is pretty cool!

Here is my user case: one bootstrap-select and one button in a line: the select for retrieving existing databases, and the button for creating a new database. I would like to use different icons in the title of select and button.

cowabunga1 's solution perfectly resolved!

**Comment by Khrysller** [comment]
+1

**Comment by Khrysller** [comment]
@caseyjhol, Do you think this feature could be added? Thanks.

**Comment by dangnelson** [comment]
+1

**Comment by jfloff** [comment]
+1

**Comment by bsurendrakumar** [comment]
+1

**Comment by huygens545** [comment]
+1

**Comment by NicolasCARPi** [comment]
Closing all old PR against master.

**Pull request closed without merging**
