### PR TITLE
Support for Bootstrap 4 - alpha6

### PR DESCRIPTION
**Pull request by infostreams**
Perhaps merge into 'bootstrap4' branch as suggested here https://github.com/silviomoreto/bootstrap-select/issues/1718 ?

### CODE REVIEW

**Comment by infostreams** [comment]
This version works with the latest Bootstrap 4 alpha. It combines snippets found on the comments sections, and an earlier commit by @hugdx. If you're uncomfortable to merge this into the master branch because Bootstrap 4 is not yet in beta, perhaps you can merge it into a separate 'bootstrap4' branch? Otherwise people who want to use your library have to maintain separate overrides, a separate fork, or (the horror) edit files in the `node_modules` directory.

**Comment by fatcrobat** [comment]
Bootstrap 4 markup for dropdowns differs from bootstrap 3. dropdown-items are now anchors and are not wrapped inside a list <ul> as list items. This pull request works not with multiple select option dropdowns.

As long as bootstrap 4 is in alpha stage,  i believe bootstrap select wont get fixed by the author.
Sadly, cause bootstrap 4 is also in alpha stage working very well.
We created a working shim repository with composer support at https://github.com/heimrichhannot/bootstrap-select if you already need bootstrap 4 support. The markup fits the new bootstrap-4 dropdown requirements.

**Comment by caseyjhol** [comment]
There have been changes in markup between the latest release of Bootstrap 4 alpha and the latest version not yet released. Most notably, the `show` class (previously `open`) is now used on the dropdown-menu element itself, rather than its parent.

**Comment by MedusaDelft** [comment]
@infostreams @fatcrobat You've probably noticed it already, but Bootstrap 4 Beta breaks the bootstrap-select alpha 4.

**Comment by fatcrobat** [comment]
@MedusaDelft Tried our version (https://github.com/heimrichhannot/bootstrap-select) with current bootstrap 4 beta version and it still works.

**Comment by MedusaDelft** [comment]
@fatcrobat Yes it works (as far as I have tested), but in bootstrap 4 beta the class  btn-secondary  has visually changed. I do now get a grey background on the 'select button' and slightly different grey placeholder-text. Also the outline (on focus) is bigger and grey, where other controls show a smaller outline and blue-ish. The control itself seems to be working (although not tested every option).

**Comment by fatcrobat** [comment]
@MedusaDelft Closest style for `btn-secondary` is now `btn-light`. Changed that in version `v1.12.5.`

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Pull request closed without merging**
