### PR TITLE
fix refresh action

### PR DESCRIPTION
**Pull request by SimonTod**
The refresh function is broken.

It duplicates the lines in the dropdown as well as the button title text.

How to reproduce :

- checkout main or dev branch.
- open tests/bootstrap5.html
- select a value with a selectpicker
- trigger the refresh function on the modified select (using browser console)

As a result :

- button title is duplicated
- drowdown elements are duplicated

### CODE REVIEW

**Comment by nftstudio** [comment]
Nice,it worked!

**Comment by cwolcott** [comment]
Fixes the basic issue for v1.14.0-beta3.

**Comment by tiesont** [comment]
@NicolasCARPi Any idea of when a new release will be pushed out? This isn't in any CDN version of which I'm aware

**Comment by NicolasCARPi** [comment]
@tiesont never. This project is completely dead and must not be used. We moved to Tom Select. Unfortunately, author didn't make it extra clear that this project is unmaintained. It should be archived.

**Pull request merged**
