### PR TITLE
Bootstrap V4-Alpha Support

### PR DESCRIPTION
**Pull request by Dinuks**
Basically just added the new V4 classes "dropdown-link" and "dropdown-item" and the "hidden" attribute to the dropdown HTML to add proper Bootstrap 4 styling.

### CODE REVIEW

**Comment by WillSquire** [comment]
Bonjour! Is the fabulous bootstrap-select ready to make its debut to Bootstrap v4 Alpha yet?

Thank you

**Comment by subramanyamVemu** [comment]
+1 for the v4 compatible version of bootstrap-select

Any release plan please

Thanks in advance

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Pull request closed without merging**
