### PR TITLE
Add bidirectional CSS support

### PR DESCRIPTION
**Pull request by elad**
Allow both left-to-right and right-to-left layouts using a single CSS file.

Supersedes #572.

### CODE REVIEW

**Comment by elad** [comment]
@t0xicCode please review this pull request as it's cleaner and more elegant than the previous one. :)

**Comment by Romainpetit** [comment]
@elad so this one can be discarded, right ?

**Comment by elad** [comment]
@Romainpetit this (#1120) pull request is the *good* one. It changes the `.less` file, which is clean.

The other (#572) pull request can be discarded - that's why I closed it myself. :)

**Comment by Romainpetit** [comment]
Alright. That looks good to me, I'd encourage @t0xicCode to merge :) :+1:

**Comment by NicolasCARPi** [comment]
Closing all old PR against master.

**Pull request closed without merging**
