### PR TITLE
Add support for UMD

### PR DESCRIPTION
**Pull request by tonyseek**
#789

Then the Browserify and Webpack will work well on bootstrap-select.

Please review it. Thanks.

### CODE REVIEW

**Comment by t0xicCode** [comment]
Could you rebase on top of master? I updated the dist files

**Comment by tonyseek** [comment]
@t0xicCode I have rebased it.

**Comment by t0xicCode** [comment]
Could this be done by using something like [efacilitation/grunt-wrap-commonjs](https://github.com/efacilitation/grunt-wrap-commonjs)?

**Comment by tonyseek** [comment]
@t0xicCode Yes. I used `grunt-umd` to achieve it.

**Comment by tonyseek** [comment]
@t0xicCode Is there anything I should do?

**Comment by tonyseek** [comment]
@silviomoreto

**Pull request merged**
